In [ ]:
Name: Dilnaz Temirbekova 180107153

## import needed libraries


In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import sklearn.model_selection as model_selection

## read the car.data

In [2]:
data = pd.read_csv("./car.data", sep = ',', header = None)
print(data)

          0      1      2     3      4     5      6
0     vhigh  vhigh      2     2  small   low  unacc
1     vhigh  vhigh      2     2  small   med  unacc
2     vhigh  vhigh      2     2  small  high  unacc
3     vhigh  vhigh      2     2    med   low  unacc
4     vhigh  vhigh      2     2    med   med  unacc
...     ...    ...    ...   ...    ...   ...    ...
1723    low    low  5more  more    med   med   good
1724    low    low  5more  more    med  high  vgood
1725    low    low  5more  more    big   low  unacc
1726    low    low  5more  more    big   med   good
1727    low    low  5more  more    big  high  vgood

[1728 rows x 7 columns]



## do the preprocessing

In [3]:
label_encoding = preprocessing.LabelEncoder()
data = data.apply(label_encoding.fit_transform)
print(data)

      0  1  2  3  4  5  6
0     3  3  0  0  2  1  2
1     3  3  0  0  2  2  2
2     3  3  0  0  2  0  2
3     3  3  0  0  1  1  2
4     3  3  0  0  1  2  2
...  .. .. .. .. .. .. ..
1723  1  1  3  2  1  2  1
1724  1  1  3  2  1  0  3
1725  1  1  3  2  0  1  2
1726  1  1  3  2  0  2  1
1727  1  1  3  2  0  0  3

[1728 rows x 7 columns]


In [4]:
x = data.values[:, 0:5]
y = data.values[:, 6]
print(x.shape)
print(y.shape)
print(x)
print(y)

(1728, 5)
(1728,)
[[3 3 0 0 2]
 [3 3 0 0 2]
 [3 3 0 0 2]
 ...
 [1 1 3 2 0]
 [1 1 3 2 0]
 [1 1 3 2 0]]
[2 2 2 ... 2 1 3]



## Apply Decision Tree Algorithm
You can use sklearn
As usual, divide the dataset for train and test

In [5]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(data[[0,1,2,3,4,5]], data[[6]], test_size = 0.5)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(864, 6) (864, 6) (864, 1) (864, 1)


In [6]:
tree=DecisionTreeClassifier()
tree.fit(x_train, y_train)
tree_pred=tree.predict(x_test)
acc=accuracy_score(y_test, tree_pred)
print("Accuracy is about ", acc*100,"%")

Accuracy is about  97.91666666666666 %


## Write your own function for f1-score

In [7]:
def precision(y_test, y_pred):
    tp = sum((y_test == 1) & (y_pred == 1))
    fp = sum((y_test == 0) & (y_pred == 1))
    p=tp / (tp + fp)
    return p
def recall(y_test, y_pred):
    tp = sum((y_test == 1)&(y_pred == 1))
    fn = sum((y_test == 1)&(y_pred == 0))
    r=tp / (fn + tp)
    return r
def f1(y_test, y_pred):
    p=precision(y_test, y_pred)
    r=recall(y_test, y_pred)
    score=2*((p * r) / (p+r))
    return score
y_test=np.array(y_test)
f1=f1(y_test.flatten(), tree_pred.flatten())
print("F1 score is about: ", f1*100,"%")

F1 score is about:  90.14084507042254 %
